src/AppBundle/Entity/Feed.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Class Feed.
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FeedRepository")
 * @ORM\HasLifecycleCallbacks
 *
 * @Vich\Uploadable
 */
class Feed
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank(message="feed.title.required")
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=false)
     * @Assert\NotBlank(message="feed.body.required")
     *
     * @var string
     */
    private $body;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="feed_image", fileNameProperty="image_name")
     *
     * @var File
     */
    private $image_file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $image_name;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank(message="feed.source.required")
     *
     * @var string
     */
    private $source;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\NotBlank(message="feed.publisher.required")
     *
     * @var string
     */
    private $publisher;

    /**
     * @ORM\Column(name="date",type="date",nullable=false)
     *
     * @var \DateTime
     */
    private $date;

    /**
     * @ORM\Column(name="created_datetime",type="datetime")
     *
     * @var \DateTime
     */
    private $created_datetime;

    /**
     * @ORM\Column(name="updated_datetime", type="datetime")
     *
     * @var \DateTime
     */
    private $updated_datetime;

    public function __construct()
    {
        $this->date = new \DateTime('now');
        $this->created_datetime = new \DateTime('now');
        $this->updated_datetime = new \DateTime('now');
    }

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->updated_datetime = new \DateTime('now');
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedDatetime()
    {
        return $this->updated_datetime;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedDatetime()
    {
        return $this->created_datetime;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param $value
     *
     * @return $this
     */
    public function setTitle($value)
    {
        $this->title = $value;

        return $this;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param $value
     *
     * @return $this
     */
    public function setBody($value)
    {
        $this->body = $value;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Feed
     */
    public function setImageFile(File $image = null)
    {
        $this->image_file = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_datetime = new \DateTime('now');
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->image_file;
    }

    /**
     * @param string $image_name
     *
     * @return Feed
     */
    public function setImageName($image_name)
    {
        $this->image_name = $image_name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->image_name;
    }

    /**
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * @param $value
     *
     * @return $this
     */
    public function setSource($value)
    {
        $this->source = $value;

        return $this;
    }

    /**
     * @return string
     */
    public function getPublisher()
    {
        return $this->publisher;
    }

    /**
     * @param $value
     *
     * @return $this
     */
    public function setPublisher($value)
    {
        $this->publisher = $value;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param \DateTime $value
     *
     * @return $this
     */
    public function setDate(\DateTime $value)
    {
        $this->date = $value;

        return $this;
    }
}

src/AppBundle/Form/Type/FeedType.php
<?php

namespace AppBundle\Form\Type;

use AppBundle\Entity\Feed;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class FeedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add('title', null, [
            'label' => 'Title',
          ])
          ->add('body', null, [
            'label' => "New's body",
          ])
          ->add('image_file', VichFileType::class, [
            'required' => false,
            'allow_delete' => true, // not mandatory, default is true
            'download_link' => true, // not mandatory, default is true
          ])
          ->add('publisher', null, [
            'label' => 'Publisher',
          ])
          ->add('source', null, [
            'label' => 'URL Source',
          ])
          ->add('date', DateType::class, [
            'label' => 'Feed date',
            'widget' => 'single_text',
          ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
          'data_class' => Feed::class,
        ]);
    }
}

src/AppBundle/Controller/FeedController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Feed;
use AppBundle\Form\Type\FeedType;
use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class FeedController extends Controller
{
    /**
     * @return Response
     *
     * @Route("/", name="feed_today")
     * @Method("GET")
     */
    public function showTodayFeedsAction()
    {
        $feeds = $this->getDoctrine()->getRepository(Feed::class)->getTodayFeeds();

        if (count($feeds) == 0) {
            $this->addFlash('warning', $this->get('translator')->trans('It seems there is no feeds registered. Maybe you need to scrap some first'));
        }

        return $this->render('AppBundle:feeds:today_feeds.html.twig', [
          'feeds' => $feeds,
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     *
     * @Route("/admin/feed/new", name="feed_new")
     * @Method({"GET","POST"})
     */
    public function newFeedAction(Request $request)
    {
        $feed = new Feed();
        $form = $this->createForm(FeedType::class, $feed, ['method' => 'POST', 'action' => $this->generateUrl('feed_new')])
          ->add('Save', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $feed = $form->getData();

            $em = $this->getDoctrine()->getManager();
            $em->persist($feed);
            $em->flush();

            $this->addFlash('success', $this->get('translator')->trans('The feed has been created'));

            return $this->redirectToRoute('feed_list');
        }

        return $this->render('@App/feeds/new_feed.html.twig', [
          'feed' => $feed,
          'form' => $form->createView(),
        ]);
    }

    /**
     * @return Response
     *
     * @Route("/admin/feed/list", name="feed_list")
     * @Method("GET")
     */
    public function getFeedsAction()
    {
        $feeds = $this->getDoctrine()->getRepository(Feed::class)->findAll();

        return $this->render('@App/feeds/list_feeds.html.twig', [
          'feeds' => $feeds,
        ]);
    }

    /**
     * @param Feed $feed
     *
     * @return Response
     *
     * @Route("/admin/feed/show/{id}", requirements={"id": "\d+"}, name="feed_show")
     * @Method("GET")
     */
    public function showFeedAction(Feed $feed)
    {
        $helper = $this->get('vich_uploader.templating.helper.uploader_helper');

        return $this->render('@App/feeds/show_feed.html.twig', [
          'feed' => $feed,
          'path' => $helper->asset($feed, 'image_file'),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     *
     * @Route("/admin/feed/update/{id}", requirements={"id": "\d+"}, name="feed_update")
     * @Method({"GET", "POST"})
     */
    public function updateFeedAction(Feed $feed, Request $request)
    {
        $form = $this->createForm(FeedType::class, $feed, ['method' => 'POST', 'action' => $this->generateUrl('feed_update', ['id' => $feed->getId()])])
          ->add('Update', SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', $this->get('translator')->trans('The feed has been updated'));

            return $this->redirectToRoute('feed_list');
        }

        return $this->render('@App/feeds/edit_feed.html.twig', [
          'feed' => $feed,
          'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     *
     * @Route("/admin/feed/delete", name="feed_delete")
     * @Method("POST")
     */
    public function deleteFeedAction(Request $request)
    {
        $feed = $this->getDoctrine()->getRepository(Feed::class)->find($request->get('id'));

        if ($feed instanceof Feed) {
            $this->getDoctrine()->getManager()->remove($feed);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', $this->get('translator')->trans('The feed has been deleted'));
        } else {
            $this->addFlash('danger', $this->get('translator')->trans('A valid feed is require for this operation'));
        }

        return $this->redirectToRoute('feed_list');
    }

    /**
     * @Route("/image/feed/{id}", requirements={"id": "\d+"}, name="load_feed_image")
     * @Method("GET")
     *
     * @param Feed $feed
     *
     * @return Response
     *
     * @throws InvalidArgumentException
     */
    public function loadFeedImageAction(Feed $feed)
    {
        return $this->get('vich_uploader.download_handler')->downloadObject($feed, 'image_file');
    }

    /**
     * @Route("/scrap-all", name="scrap_all")
     * @Method("GET")
     *
     * @return Response
     *
     * @throws InvalidArgumentException
     */
    public function scrapAllPublishersAction()
    {
        $this->get('scrapper_service')->scrapPublishers();

        $feeds = $this->getDoctrine()->getRepository(Feed::class)->findAll();

        return $this->render('@App/feeds/list_feeds.html.twig', [
          'feeds' => $feeds,
        ]);
    }
}

src/AppBundle/Resources/views/feeds/edit_feed.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <ol class="breadcrumb"><li>Admin</li><li>Edit Feed</li></ol>

  <div class="container">

    <div class="row">
      <div class="col-md-12 ">

        <h3>Edit Feed</h3>
        <hr />
        {{ form(form, {'attr': {'novalidate': 'novalidate'}}) }}

      </div>
    </div>

  </div>


{% endblock %}

src/AppBundle/Resources/views/feeds/list_feeds.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <ol class="breadcrumb"><li>Feeds</li></ol>

  <div class="container">

    <div class="row">
      <div class="col-md-12 ">

        {% include 'AppBundle:includes:flash_messages.html.twig' %}

        {% if feeds is iterable %}

          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>{% trans %}ID{% endtrans %}</th>
                  <th>{% trans %}Title{% endtrans %}</th>
                  <th>{% trans %}Publisher{% endtrans %}</th>
                  <th>{% trans %}Date{% endtrans %}</th>
                  <th class="text-center">{% trans %}Actions{% endtrans %}</th>
                </tr>
              </thead>
              {% for feed in feeds %}

                <tr>
                  <td>{{ feed.id }}</td>
                  <td>{{ feed.title }}</td>
                  <td>{{ feed.publisher }}</td>
                  <td>{{ feed.date|date("Y/m/d") }}</td>
                  <td class="text-center"> {% include '@App/feeds/includes/feed_actions.html.twig' with { 'feed' : feed } %} </td>
                </tr>
                
              {% endfor %}

            </table>
          </div>
        {% else %}
          <div class="alert alert-warning">{% trans %}There is no feed to list{% endtrans %}</div>
        {% endif %}

      </div>
    </div>

  </div>


{% endblock %}

src/AppBundle/Resources/views/feeds/new_feed.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <ol class="breadcrumb"><li>Admin</li><li>New Feed</li></ol>

  <div class="container">

    <div class="row">
      <div class="col-md-12 ">

        <h3>New Feed</h3>
        <hr />
        {{ form(form, {'attr': {'novalidate': 'novalidate'}}) }}

      </div>
    </div>

  </div>


{% endblock %}

src/AppBundle/Resources/views/feeds/show_feed.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <ol class="breadcrumb"><li>Show Feed</li></ol>

  <div class="container">

    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-12 show_feed_container">
        <h4>Feed</h4>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}ID{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.id }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Publisher{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.publisher }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Source URL{% endtrans %}
          </div>
          <div class="col-lg-8">
            <a href="{{ feed.source }}" target="_blank">Source</a>
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Title{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.title }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Body{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.body }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Image{% endtrans %}
          </div>
          <div class="col-lg-8">

            {% if feed.imageFile is not null %}
              <img src="{{ path('load_feed_image', { 'id' : feed.id }) }}" class="img-responsive" alt="Image" />
            {% else %}
              {% trans %}No image registered{% endtrans %}
            {%  endif %}

          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}News date{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.date|date("Y/m/d") }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Created at{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.createdDatetime|date("Y/m/d H:i") }}
          </div>
        </div>
        <hr />
        <div class="row show_feed_container_item_row">
          <div class="col-lg-4">
            {% trans %}Last update{% endtrans %}
          </div>
          <div class="col-lg-8">
            {{ feed.updatedDatetime|date("Y/m/d H:i") }}
          </div>
        </div>

      </div>
    </div>

  </div>


{% endblock %}

src/AppBundle/Resources/views/feeds/today_feeds.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <ol class="breadcrumb"><li>Today Feeds ( {{ 'now'|date('Y-m-d')}} )</li></ol>

  <div class="container">

    <div class="row">
      <div class="col-md-12 ">

        {% include 'AppBundle:includes:flash_messages.html.twig' %}

        {% if feeds is iterable %}
          <div class="row">

          {% for feed in feeds %}

            <div class="col-sm-12 col-md-6">
              <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">{{ feed.publisher }} <a class="btn btn-xs btn-default" href="{{ path('feed_show',{ 'id' : feed.id }) }}">{{ "Full view"|trans }}</a> </h3>
                </div>
                <div class="panel-body">

                  <p><strong>{{ feed.title }}</strong></p>

                  {% if feed.imageFile is not null %}
                    <img src="{{ path('load_feed_image', { 'id' : feed.id }) }}" class="img-responsive" alt="Image" />
                  {% else %}
                    {% trans %}No image registered{% endtrans %}
                  {%  endif %}

                  <p>{{ feed.body }}</p>

                </div>
              </div>
            </div>

          {% endfor %}

          </div>
        {% endif %}

      </div>
    </div>

  </div>


{% endblock %}